export interface FrequencyEntry {
  range: string;
  title: string;
  summary: string;
  ruTitle: string;
  ruSummary: string;
}

export const FREQUENCY_ENCYCLOPEDIA: FrequencyEntry[] = [
  { range: '0-1 Hz', title: 'Infrasonic drift', summary: 'Below normal hearing. Reproduced as slow pressure modulation only on capable transducers; no universal biological effect is established.', ruTitle: 'Инфранизкая модуляция', ruSummary: 'Ниже обычного слуха. Воспроизводится только как медленная модуляция давления на подходящих излучателях; универсальный биологический эффект не установлен.' },
  { range: '1-4 Hz', title: 'Delta-rate modulation', summary: 'A modulation-rate range used in sleep research. It is not a direct sleep switch and must not be treated as a medical intervention.', ruTitle: 'Дельта-модуляция', ruSummary: 'Диапазон частот модуляции, используемый в исследованиях сна. Это не переключатель сна и не медицинское вмешательство.' },
  { range: '4-8 Hz', title: 'Theta-rate modulation', summary: 'A modulation-rate range associated with drowsiness and memory experiments; perception depends on level, carrier and listener.', ruTitle: 'Тета-модуляция', ruSummary: 'Диапазон модуляции, встречающийся в исследованиях сонливости и памяти; восприятие зависит от уровня, несущей и слушателя.' },
  { range: '8-14 Hz', title: 'Alpha-rate modulation', summary: 'A modulation range commonly measured during relaxed wakefulness. Audio entrainment claims beyond that observation are not guaranteed.', ruTitle: 'Альфа-модуляция', ruSummary: 'Диапазон модуляции, часто измеряемый при спокойном бодрствовании. Более сильные заявления об аудиосинхронизации не гарантируются.' },
  { range: '14-30 Hz', title: 'Beta-rate modulation', summary: 'A modulation range used in attention and motor studies. It can sound like a distinct pulse when applied to an audible carrier.', ruTitle: 'Бета-модуляция', ruSummary: 'Диапазон модуляции, используемый в исследованиях внимания и моторики. На слышимой несущей воспринимается как отдельный пульс.' },
  { range: '30-80 Hz', title: 'Low-gamma modulation', summary: 'Fast amplitude modulation that remains audible on a carrier and is used in auditory perception experiments.', ruTitle: 'Низкогамма-модуляция', ruSummary: 'Быстрая амплитудная модуляция, слышимая на несущей и применяемая в экспериментах слухового восприятия.' },
  { range: '80-250 Hz', title: 'Low-frequency audible', summary: 'Bass fundamentals with long wavelengths. Room modes and transducer excursion dominate the result more than the nominal number.', ruTitle: 'Низкочастотный слышимый диапазон', ruSummary: 'Басовые основы с большой длиной волны. Результат сильнее зависит от мод помещения и хода динамика, чем от номинальной цифры.' },
  { range: '250-500 Hz', title: 'Low-mid body', summary: 'A major region for warmth and body in voices and instruments; excessive energy can make a mix sound muddy.', ruTitle: 'Нижняя середина', ruSummary: 'Основная область плотности и теплоты голосов и инструментов; избыток энергии делает звучание мутным.' },
  { range: '500-1,000 Hz', title: 'Midrange fundamentals', summary: 'Contains many speech and instrument fundamentals. The ear is highly sensitive to level changes here.', ruTitle: 'Среднечастотные основы', ruSummary: 'Содержит многие основы речи и инструментов. Ухо особенно чувствительно к изменению уровня в этой области.' },
  { range: '1-2 kHz', title: 'Speech intelligibility body', summary: 'Important for vowel definition and the perceived forwardness of many sources.', ruTitle: 'Разборчивость речи', ruSummary: 'Важна для формирования гласных и ощущения близости многих источников.' },
  { range: '2-4 kHz', title: 'Presence and consonants', summary: 'Strongly contributes to speech intelligibility and attack. High levels can sound hard or fatiguing.', ruTitle: 'Присутствие и согласные', ruSummary: 'Сильно влияет на разборчивость речи и атаку. Высокий уровень может звучать резко и утомлять.' },
  { range: '4-6 kHz', title: 'Clarity band', summary: 'Adds edge and detail to transients. Excessive exposure increases perceived harshness.', ruTitle: 'Диапазон ясности', ruSummary: 'Добавляет детализацию атакам. Избыточная экспозиция усиливает ощущение резкости.' },
  { range: '6-8 kHz', title: 'Sibilance region', summary: 'Contains much of the energy of s, sh and cymbal transients; de-essing often works here.', ruTitle: 'Область сибилянтов', ruSummary: 'Содержит значительную энергию звуков с, ш и атак тарелок; здесь часто работает de-esser.' },
  { range: '8-12 kHz', title: 'Brilliance', summary: 'Adds brightness and perceived detail to cymbals and noise textures.', ruTitle: 'Блеск', ruSummary: 'Добавляет яркость и ощущение деталей тарелкам и шумовым текстурам.' },
  { range: '12-16 kHz', title: 'Air transition', summary: 'High-frequency detail is increasingly dependent on age, hearing health and playback hardware.', ruTitle: 'Переход к воздуху', ruSummary: 'Высокочастотные детали всё сильнее зависят от возраста, слуха и аппаратуры.' },
  { range: '16-20 kHz', title: 'Upper audible limit', summary: 'Near the nominal upper hearing limit for young listeners; many systems roll off before this region.', ruTitle: 'Верхняя граница слышимости', ruSummary: 'Близко к условной верхней границе слуха молодых слушателей; многие системы затухают раньше.' },
  { range: '20-22.05 kHz', title: 'High-resolution audio edge', summary: 'Usually requires a 44.1 kHz system for representation and a suitable transducer for output.', ruTitle: 'Край high-resolution', ruSummary: 'Для представления обычно требуется система 44,1 кГц и подходящий излучатель.' },
  { range: '22.05-24 kHz', title: '96 kHz headroom', summary: 'Representable by 48 kHz and higher sample-rate systems; normally inaudible to humans.', ruTitle: 'Запас системы 96 кГц', ruSummary: 'Представимо системами от 48 кГц; обычно не слышно человеку.' },
  { range: '24-30 kHz', title: 'Ultrasonic hardware band', summary: 'Outside normal human hearing. Output is hardware-dependent and should be kept at safe levels.', ruTitle: 'Ультразвуковой аппаратный диапазон', ruSummary: 'За пределами обычного слуха. Вывод зависит от аппаратуры и должен оставаться на безопасном уровне.' },
];
